In [2]:
import numpy as np
from numpy import array

更改ndarray维度

In [3]:
nd_array = array([[1, 2, 3], [4, 5, 6]])

print("reshape: ", nd_array)

new_nd_array = nd_array.reshape((3, 2)) # 改变数组形状
print("reshape: ", new_nd_array)

new_nd_array = new_nd_array.flatten()   # 将多维数组展开为一维
print("reshape: ", new_nd_array)

reshape:  [[1 2 3]
 [4 5 6]]
reshape:  [[1 2]
 [3 4]
 [5 6]]
reshape:  [1 2 3 4 5 6]


In [4]:
a = array([1, 2, 3, 4])
b = array([10, 20, 30, 40])

* 合并a和b

In [14]:
print(np.hstack([a, b])) # 水平拼接数组
print(np.vstack([a, b])) # 垂直拼接数组
print(np.concatenate([a, b], axis=0)) # 按指定维度拼接数组

[ 1  2  3  4 10 20 30 40]
[[ 1  2  3  4]
 [10 20 30 40]]
[ 1  2  3  4 10 20 30 40]


In [23]:
# 解释axis
c = np.arange(81).reshape((3,3,3,3))
d = np.array(range(81)).reshape((3,3,3,3))

print('c.shape: ', c.shape)
print('d.shape: ', d.shape)
res = np.concatenate([c, d], axis=0)
print('res.shape: ', res.shape)

c.shape:  (3, 3, 3, 3)
d.shape:  (3, 3, 3, 3)
res.shape:  (3, 3, 6, 3)


* ndarray的条件选择计算

a和b的条件拼接

In [29]:
a = array([1, 2, 3, 4])
b = array([10, 20, 30, 40])

c = array([-1, 1, 1, -1])

In [31]:
result = np.where(c > 0, a, b)	# 满足条件则取 x，否则取 y，所以 0 位是 False，取 b 的值，1 位是 True，取 a 的值
print(result)

print('c > 0', c > 0) # 返回一个布尔数组，比如 c > 0 返回 [False  True  True False]

[10  2  3 40]
c > 0 [False  True  True False]


In [32]:
conditions = [a < 2, a > 2]
choices = [a * 10, a * 100]
# 当 a < 2 时，返回 a * 10，否则返回 a * 100
# 所以 [1, 2, 3, 4] -> [1 * 10, 2 * 100, 3 * 100, 4 * 100]
result = np.select(conditions, choices, default=0)
print(result)

[ 10   0 300 400]


* 提示：回想一下 `switch case`，思考`np.select`的设计，查阅并核实你对该 api 的猜测